ce-evals-app/config/routes.rb
Rails.application.routes.draw do

  root to: "application#index"

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'admin', to: 'admin#index'


  # resources :users, :only => [:index, :update] do
  #   get :me, on: :collection
  # end


   resources :users do
     patch 'update_role', on: :member
     get 'assign_role', on: :member
      collection do
        get 'unassigned'
      end
   end

   resources :attendees do
     collection {post :import}
     get 'profile', on: :member
     resources :evaluations do
       get 'answers', on: :member
     end
   end

   resources :courses do
     collection {get :finished}
     collection {get :draft}
     collection {get :current}
     collection {get :upcoming}
     get 'report', on: :member
     collection {post :import}
     resources :attendees do
       resource :download, only: [:show]
     end
   end

   resources :instructors do
     get 'profile', on: :member
   end

   resources :questions

   resources :evaluations do
     collection {get :assigned}
     collection {get :unassigned}
     get 'answers', on: :member
   end

   resources :finished_evaluations do
     get 'answers', on: :member
   end

end

ce-evals-app/app/models/instructor.rb
class Instructor < ApplicationRecord
  has_many :courses
  has_many :attendees, :through => :courses
  belongs_to :user, optional: true

  validates :first_name, presence: true, length: { minimum: 2 }
  validates :last_name, presence: true, length: { minimum: 2 }

  def fullname
    "#{first_name} #{last_name}"
  end

end

ce-evals-app/app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :profile, :edit, :update, :destroy]

  def index
    @instructors = Instructor.all
  end

  def show
  end

  def profile
  end

  def new
    @instructor = Instructor.new
  end

  def create
    @instructor = Instructor.new(instructor_params)
    if @instructor.save
      redirect_to @instructor, notice: 'Instructor was successfully created.'
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if @instructor.update(instructor_params)
      redirect_to profile_instructor_path(@instructor), notice: 'Instructor was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @instructor.destroy
    redirect_to instructors_url, notice: 'Instructor was successfully deleted.'
  end

private

  def set_instructor
    @instructor = Instructor.find(params[:id])
  end

  def instructor_params
    params.require(:instructor).permit(:first_name, :last_name, :title, :suffix, :instructor_ids => [])
  end

end

ce-evals-app/app/views/instructors/_form.html.erb
<%= form_for @instructor, builder: PrimerFormBuilder do |f| %>
  <% if @instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instructor.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @instructor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %><br>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %><br>
    <%= f.label :title %><br>
    <%= f.text_field :title %><br>
    <%= f.label :suffix %><br>
    <%= f.text_field :suffix %><br>
  </div>
</br>
  <div class="actions">
    <%= f.submit 'Update Profile', :class => 'btn btn-primary' %>
  </div>
<% end %>

ce-evals-app/app/views/instructors/edit.html.erb
<h3>Editing Your Profile</h3>

<%= render 'form' %>

ce-evals-app/app/views/instructors/index.html.erb
<% if is_superadmin? %>
  <%= link_to "New Instructor", new_instructor_path, class: "btn btn-primary" %>
<% end %>
  <div class="columns">
    <% @instructors.each_slice(10) do |instructors| %>
        <div class="one-fifth column">
          <table class="data-table">
            <tr>
              <th>Name</th>
            </tr>
              <% instructors.each do |i| %>
                <tr>
                  <td>
                      <%= link_to i.fullname, instructor_path(i) %>
                  </td>
                </tr>
              <% end %>
        </table>
      </div>
    <% end %>
  </div>

<br />
<br />

ce-evals-app/app/views/instructors/new.html.erb
<h1>New Instructor</h1>

<%= render 'form' %>

ce-evals-app/app/views/instructors/profile.html.erb
<h3>You are an instructor. </br></br>
Title: <%= @instructor.title %></br>
First name: <%= @instructor.first_name %></br>
Last name: <%= @instructor.last_name %></br>
Suffix: <%= @instructor.suffix %></br>
</h3>
</br>
<%= link_to 'Edit Profile', edit_instructor_path(@instructor), class: 'btn'%>
</br></br>
<h3>Email: <%= current_user.email %></h3>
</br>
<%= link_to 'Update Login Email or Password', edit_user_registration_path, class: 'btn'%>

ce-evals-app/app/views/instructors/show.html.erb
  <h2>Courses taught by: <%= @instructor.title %> <%= @instructor.fullname %>, <%= @instructor.suffix %> </h2>
    <table class="data-table">
        <tr>
        <th>Course Title</th>
        <th>End Date</th>
        <th>Credits</th>
        <th>Location</th>
        <% if is_authorized?(@instructor) %>
          <th>Action</th>
        <% end %>
      </tr>
      <% @instructor.courses.each do |c| %>
      <tr>
          <td>
              <%= link_to c.title, c %>
          </td>
          <td>
            <%= c.end_date.strftime("%A, %b %d") %>
          </td>
          <td>
            <%= c.credits %>
          </td>
          <td>
            <%= c.location %>
          </td>
          <% if is_authorized?(@instructor) %>
            <td>
            <% if c.evaluation.nil? %>
                <%= link_to "Assign Eval", unassigned_evaluations_path %>
            <% else %>
              <% if c.complete? && c.finished_evaluations.any? %>
                <%= link_to "Report", report_course_path(c) %>
              <% else %>
                <%= c.evaluation.name %>
              <% end %>
            <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </table>
  <br />
  <% if is_superadmin? %>
    <%= link_to 'Edit', edit_instructor_path(@instructor), class: "btn" %> |
    <%= link_to 'Destroy', @instructor, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>