ce-evals-app/config/routes.rb
Rails.application.routes.draw do

  root to: "application#index"

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'admin', to: 'admin#index'


  # resources :users, :only => [:index, :update] do
  #   get :me, on: :collection
  # end


   resources :users do
     patch 'update_role', on: :member
     get 'assign_role', on: :member
      collection do
        get 'unassigned'
      end
   end

   resources :attendees do
     collection {post :import}
     get 'profile', on: :member
     resources :evaluations do
       get 'answers', on: :member
     end
   end

   resources :courses do
     collection {get :finished}
     collection {get :draft}
     collection {get :current}
     collection {get :upcoming}
     get 'report', on: :member
     collection {post :import}
     resources :attendees do
       resource :download, only: [:show]
     end
   end

   resources :instructors do
     get 'profile', on: :member
   end

   resources :questions

   resources :evaluations do
     collection {get :assigned}
     collection {get :unassigned}
     get 'answers', on: :member
   end

   resources :finished_evaluations do
     get 'answers', on: :member
   end

end

ce-evals-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, :only => [:index]

  def index
    unless current_user.nil?
      redirect_to home
    end
  end

  private

  def home
    if current_user.attendee_role && !current_user.attendee.nil?
      attendee_url(user.attendee)
    elsif current_user.instructor_role
      instructor_url(user.instructor)
    elsif current_user.superadmin_role
      admin_path
    else
      unassigned_users_path
    end
  end

  protected
    # These are the custom redirects for successful sign ins.
    # def after_sign_in_path_for(resource)
    #   # if the user is an attendee, redirect them to their show page
    #   if current_user.attendee_role && current_user.attendee
    #      attendee_url(current_user.attendee)
    #   # if the user is an instructor, redirect them to their show page
    # elsif current_user.instructor_role && current_user.instructor
    #     instructor_url(current_user.instructor)
    #   # if the user is a superadmin, redirect them to the attendees index
    #   elsif current_user.superadmin_role
    #     admin_path
    #   # else, redirect them to a page that tells them to sit tight until they are assigned a role
    #   else
    #     root_url #I need to create a page for users who are not yet assigned
    #   end
    #end

end

ce-evals-app/app/helpers/application_helper.rb
module ApplicationHelper
end

ce-evals-app/app/views/application/_edit_destory.html.erb
<%= link_to 'Edit', edit_attendee_path(@attendee) %> |
<%= link_to 'Destroy', @attendee, method: :delete, data: { confirm: 'Are you sure?' } %>

ce-evals-app/app/views/application/_footer.html.erb
<div class="footer container-lg px-3">
  <div class="position-relative d-flex flex-justify-between py-6 mt-6 f6 text-gray border-top border-gray-light">
    © 2018 John Fewell   
  </div>
</div>

ce-evals-app/app/views/application/_logged_out_header.html.erb
<nav class="UnderlineNav UnderlineNav--full" aria-label="Menu">
 <div class="container-lg UnderlineNav-container">
   <div class="UnderlineNav-body">
      <%= image_tag "ce-cert-logo.png" %> <h1>Continuing Education Certificates</h1>
    </div>
  </div>
</nav>

ce-evals-app/app/views/application/_nav.html.erb
<nav class="UnderlineNav UnderlineNav--full" aria-label="Menu">

 <div class="container-lg UnderlineNav-container">
   <div class="UnderlineNav-body">
     <%= image_tag "ce-cert-logo.png" %>
     <%= link_to "Home", home(current_user), :class => home_page?(home(current_user)) %>
     <% if is_superadmin? %>
      <%= link_to "Instructors", instructors_path, :class => current_class?(instructors_path)  %>
     <% end %>
     <% unless is_attendee? %>
      <%= link_to "Courses", courses_path, :class => current_class?(courses_path) %>
      <%= link_to "Attendees", attendees_path, :class => current_class?(attendees_path)  %>
      <%= link_to "Evaluations", evaluations_path, :class => current_class?(evaluations_path)  %>
      <%= link_to "Questions", questions_path, :class => current_class?(questions_path)  %>
     <% end %>
     <% if is_superadmin? %>
      <%= link_to "Users", users_path, :class => current_class?(users_path)  %>
      <%= link_to "Finished Evals", finished_evaluations_path, :class => current_class?(finished_evaluations_path)  %>
     <% end %>
    </div>
     <div class="float-right UnderlineNav-body">
       <% unless !user_assigned?(current_user) %>
        <%= link_to profile(current_user), class: "UnderlineNav-item" do %>
        <%= octicon "person" %>
        Profile
        <% end %>
       <% end %>
       <%= link_to destroy_user_session_path, method: :delete, class: "UnderlineNav-item" do %>
        <%= octicon "sign-out" %>
        Logout
       <% end %>
     </div>
   </div>
</nav>

ce-evals-app/app/views/application/_unassigned_user_nav.html.erb
<nav class="UnderlineNav UnderlineNav--full" aria-label="Menu">

 <div class="container-lg UnderlineNav-container">
   <div class="UnderlineNav-body">
     <%= image_tag "ce-cert-logo.png" %>
     <%= link_to "Home", unassigned_users_path %>
       <%= link_to destroy_user_session_path, method: :delete, class: "UnderlineNav-item" do %>
        <%= octicon "sign-out" %>
        Logout
       <% end %>
     </div>
   </div>
</nav>

ce-evals-app/app/views/application/index.html.erb
<%= link_to new_user_session_path, class: 'btn btn-primary btn-large f4 btn-block' do %>Sign in<% end %>
<%= link_to new_user_registration_path, class: 'btn btn-primary btn-large f4 btn-block' do %>Register<% end %>
<%= link_to user_facebook_omniauth_authorize_path, class: 'btn btn-primary btn-large f4 btn-block' do %>Sign in or sign up with Facebook<% end %>