ce-evals-app/config/routes.rb
Rails.application.routes.draw do

  root to: "application#index"

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'admin', to: 'admin#index'


  # resources :users, :only => [:index, :update] do
  #   get :me, on: :collection
  # end


   resources :users do
     patch 'update_role', on: :member
     get 'assign_role', on: :member
      collection do
        get 'unassigned'
      end
   end

   resources :attendees do
     collection {post :import}
     get 'profile', on: :member
     resources :evaluations do
       get 'answers', on: :member
     end
   end

   resources :courses do
     collection {get :finished}
     collection {get :draft}
     collection {get :current}
     collection {get :upcoming}
     get 'report', on: :member
     collection {post :import}
     resources :attendees do
       resource :download, only: [:show]
     end
   end

   resources :instructors do
     get 'profile', on: :member
   end

   resources :questions

   resources :evaluations do
     collection {get :assigned}
     collection {get :unassigned}
     get 'answers', on: :member
   end

   resources :finished_evaluations do
     get 'answers', on: :member
   end

end

ce-evals-app/app/controllers/courses_controller.rb
require 'pry'
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy, :report]
  before_action :is_authorized?, only: [:edit, :update, :destroy, :draft]
  before_action :is_authorized_index_new, only: [:new, :report]

  def index
    @courses = Course.all
  end

  def finished
    @courses = Course.complete.published
  end

  def current
    @courses = Course.not_complete.started.published
  end

  def upcoming
    @courses = Course.upcoming.published
  end

  def draft
    @courses = []
    if current_user.instructor_role?
      Course.unpublished.each do |c|
        if c.instructor_id == current_user.instructor.id
          @courses << c
        end
      end
    else
      @courses = Course.unpublished
  end
end

  def show
    if @course.published == false
      flash[:alert] = "This course is unpublished"
    end
  end

  def new
    @course = Course.new
  end

  def report
    if @course.finished_evaluations.count > 0
      percent = @course.finished_evaluations.count.to_f / @course.attendees.count.to_f * 100
      @evaluation_completed_percent = percent.round(2)
    else
      @evaluation_completed_percent = 0
    end

    @course.finished_evaluations.last.questions_ratings_hash

    keys = []
    values = []
    @course.finished_evaluations.each do |fe|
      fe.answers.each do |a|
        if a.content.nil?
          values << a.rating.average.to_f
          keys << a.question.content
        end
      end
    end
    @questions_ratings_hash =  Hash[keys.zip(values)]

    keys = []
    values = []
    @course.finished_evaluations.each do |fe|
      fe.answers.each do |a|
        if !a.content.nil?
          values << a.content
          keys << a.question.content
        end
      end
    end
    pairs = keys.zip(values)
    @questions_answers_hash = pairs.group_by(&:first)
    @questions_answers_hash.keys.each {
      |k| @questions_answers_hash[k] = @questions_answers_hash[k].map(&:last) }
  end

  def import
    course = Course.find(params[:id])
    Attendee.import(params[:file], course)
    redirect_to course_path(course), notice: "Attendee data imported!"
  end

  def edit
    if current_user.attendee_role?
      redirect_to root_path, alert: "You aren't authorized to do that"
    end
  end

  def create
  @course = Course.new(course_params)
    if @course.save
      redirect_to @course, notice: 'Course was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @course.update(course_params)
      redirect_to @course, notice: 'Course was successfully updated.'
    else
      format.html { render :edit }
    end

  end

  def destroy
    if @course.finished_evaluations.any? && current_user.instructor_role
      redirect_to @course, alert: "You can't delete this course, it has finished evalutions. Contact the admin if you think it should be deleted."
    else
      #@course.destroy
      redirect_to courses_url, notice: 'Course was successfully deleted.'
    end
  end

private

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :location, :credits, :learning_objective_1, :learning_objective_2, :learning_objective_3, :start_date, :end_date, :published, :instructor_id, :evaluation_id)
  end

  def is_authorized_index_new
    if current_user.attendee_role
      redirect_to root_path, alert: "You can't do that"
    elsif current_user.instructor_role
      if current_user.instructor.courses.find(params[:id]).nil?
        redirect_to root_path, alert: "You can't do that"
      end
    elsif current_user.superadmin_role?
      true
    else
      redirect_to root_path, alert: "Something bizzare happened"
    end
  end

  def is_authorized?
    if current_user.superadmin_role
      true
    elsif current_user.instructor_role
      true
    elsif current_user.attendee_role
      if !current_user.attendee.courses.find(params[:id]).nil?
        true
      else
        redirect_to root_url, alert: "You aren't authorized to see that page."
      end
    else
      redirect_to root_url, alert: "Something weird happened."
    end
  end

end

ce-evals-app/app/views/courses/_courses_status.html.erb
<%= render 'courses_subnav' %>
<ul>
  <% @courses.each do |c| %>
    <% if is_authorized?(c) %>
      <li class="col-12 d-block width-full py-4 border-bottom public source" itemprop="owns" itemscope="" itemtype="http://schema.org/Code">
        <div class="d-inline-block mb-1">
          <h3>
            <%= link_to c.title, course_path(c), itemprop: "name codeRepository" %>
          </h3>
        </div>
        <div class="f6 text-gray mt-2">
              <span class="mr-3" itemprop="programmingLanguage">
                Instructor: <%= c.instructor.title %> <%= c.instructor.fullname %>, <%= c.instructor.suffix %>
              </span>
            Date: <%= c.start_date %>
        </div>
      </li>
    <% end %>
  <% end %>
</ul>

ce-evals-app/app/views/courses/_courses_subnav.html.erb
<div class="tabnav">
  <div class="float-right">
    <% unless is_attendee? %>
      <%= link_to "New Course", new_course_path, class: "tabnav-extra btn" %>
      <%= link_to "Draft Courses", draft_courses_path, class: "tabnav-extra" %>
    <% end %>
  </div>
  <nav class="tabnav-tabs" aria-label="All Courses">

    <%= link_to courses_path, :class => current_page?(courses_path) do %>
      All Courses
      <span class="Counter"><%= courses_published_count %></span>
    <% end %>

    <%= link_to finished_courses_path, :class => current_page?(finished_courses_path) do %>
      Finished Courses
      <span class="Counter"><%= courses_finished_count %></span>
    <% end %>

    <%= link_to current_courses_path, :class => current_page?(current_courses_path) do %>
    Current Courses
      <span class="Counter"><%= courses_current_count %></span>
    <% end %>

    <%= link_to upcoming_courses_path, :class => current_page?(upcoming_courses_path) do %>
    Upcoming Courses
      <span class="Counter"><%= courses_upcoming_count %></span>
    <% end %>

  </nav>
</div>

ce-evals-app/app/views/courses/_form.html.erb
<%= form_for @course, builder: PrimerFormBuilder do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <dl class="form-group">
    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %><br>
      <%= f.label :location %><br>
      <%= f.text_field :location %><br>
      <%= f.label :credits %><br>
      <%= f.number_field :credits %><br>
      <%= f.label :learning_objective_1 %><br>
      <%= f.text_field :learning_objective_1 %><br>
      <%= f.label :learning_objective_2 %><br>
      <%= f.text_field :learning_objective_2 %><br>
      <%= f.label :learning_objective_3 %><br>
      <%= f.text_field :learning_objective_3 %><br>
      <%= f.label :start_date %><br>
      <%= f.date_field :start_date %><br>
      <%= f.label :end_date %><br>
      <%= f.date_field :end_date %><br>
    </div>
    <div class="form-checkbox">
      <label>
        <%= f.label :published %>
        <%= f.check_box :published %>
      </label>
      <p class="note" id="help-text-for-checkbox">
        Leave this <strong>unchecked</strong> if you don't want students to be able to register for this yet.
      </p>
    </div>
  </dl>
  <h3>Instructor</h3>
    <% if current_user.instructor_role %>
      <%= f.hidden_field :instructor_id, :value => current_user.instructor.id %>
      <%= current_user.instructor.fullname %> - You!
    <% else %>
      <div class="field mx-5">
        <%= f.collection_radio_buttons(:instructor_id, Instructor.all, :id, :fullname) do |b| %>
          <%= b.label class:"form-checkbox" do%>
            <%=b.radio_button + b.text%> </br>
          <%end%>
        <% end %>
      </div>
    <% end %>
    <br /><br />
  <h3>Evaluation</h3>
  
  <div class="field mx-5">
    <%= f.collection_radio_buttons(:evaluation_id, Evaluation.unassigned, :id, :name) do |b| %>
      <%= b.label class:"form-checkbox" do%>
        <%=b.radio_button + b.text%> </br>
      <%end%>
    <% end %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

ce-evals-app/app/views/courses/current.html.erb
<%= render 'courses_status' %>

ce-evals-app/app/views/courses/draft.html.erb
<%= render 'courses_status' %>

ce-evals-app/app/views/courses/edit.html.erb
<h1>Editing Course: <%= @course.title %></h1>

<%= render 'form' %>

ce-evals-app/app/views/courses/finished.html.erb
<%= render 'courses_status' %>

ce-evals-app/app/views/courses/index.html.erb
<%= render 'courses_status' %>

ce-evals-app/app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

ce-evals-app/app/views/courses/report.html.erb
<h2><%= @course.title %> - Report</h2>
<br />
Number of attendees: <%= @course.attendees.count  %></br>
Percent with complete evaluations: <%= @evaluation_completed_percent %>%
<br /><br />
<h4>Quantitative Questions</h4>
<table class="data-table">
  <tr>
    <th>Question</th>
    <th>Average Rating</th>
  </tr>

  <% @course.finished_evaluations.last.questions_ratings_hash.each do | question, rating |%>
  <tr>
    <td>
      <%= question %>
    </td>

    <td>
      <%= rating %>
    </td>
  </tr>

  <% end %>
</table>

<br />

<h4>Qualitative Questions</h4>

<% @questions_answers_hash.each do |k, v|%>
<table class="data-table">
  <tr>
    <th>Question: <%= k %></th>
  </tr>
  <% v.each do |v| %>
    <tr>
      <td>
        <%= v %>
      </td>
    </tr>
  <% end %>
</table>
<% end %>

ce-evals-app/app/views/courses/show.html.erb
<% if is_authorized?(@course) && @course.finished_evaluations.any? %>

  <%= link_to 'View Report', report_course_path(@course), class: "btn btn-primary" %>
  <br /><br />
<% end %>
<h2><%= @course.title %></h2>
<div class="mx-5">
  <ul>
    <li>Instructor: <%= link_to @course.instructor.fullname, @course.instructor %></a></li>
    <li>Location: <%= @course.location %></li>
    <li>Credits: <%= @course.credits %></li>
    <li>Start Date: <%= @course.start_date %></li>
    <li>End Date: <%= @course.end_date %></li>
    <li>Learning Objective 1: <%= @course.learning_objective_1 %></li>
    <li>Learning Objective 2: <%= @course.learning_objective_2 %></li>
    <li>Learning Objective 3: <%= @course.learning_objective_3 %></li>
  </ul>
</div>
</br>

<% if is_authorized?(@course) %>

  <h3>Attendees</h3>
    <div class="mx-5">
      <% if @course.attendees.any? %>
        <ul>
            <% @course.attendees.each do |a| %>
            <li>
              <%= link_to a.fullname, attendee_path(a) %>
            </li>
            <% end %>
        </ul>
        <% else %>
        None
      <% end %>
    </div>
  <br />

  <h3>Evaluation Name:

      <% if !@course.evaluation.nil?  %>
        <%= @course.evaluation.name %></h3>
      <% else %>
        <%= link_to "Not assigned - Create one", new_evaluation_path%></h3>
      <% end %>

  <% if @course.complete? %>
    <br />
    <h3>Finished Evaluations:
        <% if !@course.finished_evaluations.nil?  %>
          <%= @course.finished_evaluations.count %></h3>
        <% else %>
          None completed</h3>
        <% end %>

  <% end %>
  <br />
  <h3>Import Attendees</h3>
  <br>
  <%= form_tag import_courses_path, id: params[:id], multipart: true do %>
  <%= hidden_field_tag :id , params[:id] %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import CSV" %>
  <% end %>

  <br />
  <br />

  <%= link_to 'Edit', edit_course_path(@course), class: "btn" %> |
  <%= link_to 'Destroy', @course, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

ce-evals-app/app/views/courses/upcoming.html.erb
<%= render 'courses_status' %>