ce-evals-app/config/routes.rb
Rails.application.routes.draw do

  root to: "application#index"

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'admin', to: 'admin#index'


  # resources :users, :only => [:index, :update] do
  #   get :me, on: :collection
  # end


   resources :users do
     patch 'update_role', on: :member
     get 'assign_role', on: :member
      collection do
        get 'unassigned'
      end
   end

   resources :attendees do
     collection {post :import}
     get 'profile', on: :member
     resources :evaluations do
       get 'answers', on: :member
     end
   end

   resources :courses do
     collection {get :finished}
     collection {get :draft}
     collection {get :current}
     collection {get :upcoming}
     get 'report', on: :member
     collection {post :import}
     resources :attendees do
       resource :download, only: [:show]
     end
   end

   resources :instructors do
     get 'profile', on: :member
   end

   resources :questions

   resources :evaluations do
     collection {get :assigned}
     collection {get :unassigned}
     get 'answers', on: :member
   end

   resources :finished_evaluations do
     get 'answers', on: :member
   end

end

ce-evals-app/app/models/evaluation.rb
class Evaluation < ApplicationRecord
  has_many :evaluation_questions
  has_many :questions, :through => :evaluation_questions
  belongs_to :course, optional: true
  has_many :finished_evaluations
  accepts_nested_attributes_for :questions, reject_if: lambda {|attributes| attributes['content'].blank?}

  validates :name, presence: true, length: { minimum: 5 }

  scope :unassigned, -> {where(:course_id => nil)}
  scope :assigned, -> {where.not(:course_id => nil)}


end

ce-evals-app/app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
   before_action :set_evaluation, only: [:show, :edit, :update, :destroy, :answers]
   before_action :is_authorized?, only: [:index, :new, :show, :edit, :update, :destroy]

  def index
    @evaluations = Evaluation.all
  end

  def show
    @questions = @evaluation.questions
  end

  def assigned
    @evaluations = Evaluation.assigned
  end

  def unassigned
    @evaluations = Evaluation.unassigned
  end

  def answers
    #prevent instructors from completing evaluations
    if current_user.instructor_role?
      redirect_to profile_instructor_path, alert: "You can't complete evaluation forms."

    #checks to see if the current_user is acess
    elsif params[:attendee_id] == current_user.attendee.id.to_s || current_user.superadmin_role?
      @attendee = Attendee.find(params[:attendee_id])
      evaluation = Evaluation.find(params[:id])
      @course = Course.find(evaluation.course.id)

      if !@attendee.courses.include?(@course)
        redirect_to @attendee, alert: "#{@attendee.fullname} was not registered for this course."
      end

      if !@course.complete?
        redirect_to @attendee, alert: "#{@course.title} is not over yet."
      end

      @finished_evaluation = FinishedEvaluation.new
      @questions = @evaluation.questions
    else
      redirect_to root_path, alert: "Don't try to URL hack me."
    end
  end

  def new
    @evaluation = Evaluation.new
  end

  def edit
  end

  def create
    @evaluation = Evaluation.new(evaluation_params)
    if @evaluation.save
      redirect_to @evaluation, notice: 'Evaluation was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @evaluation.update(evaluation_params)
      redirect_to @evaluation, notice: 'Evaluation was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @evaluation.destroy
    redirect_to evaluations_url, notice: 'Evaluation was successfully deleted.'
  end

  private

  def set_evaluation
    @evaluation = Evaluation.find(params[:id])
  end

  def evaluation_params
    params.require(:evaluation).permit(:name, :course_id, :question_ids => [], :questions_attributes => [:content])
  end

  def is_authorized?
    if current_user.superadmin_role
      true
    elsif current_user.instructor_role
      true
    elsif current_user.attendee_role
      redirect_to profile_attendee_path(current_user.attendee.id), alert: "You aren't authorized to see that page."
    else
      redirect_to root_url, alert: "Something weird happened."
    end
  end

end

ce-evals-app/app/helpers/evaluation.rb
class Evaluation < ApplicationRecord
  has_many :evaluation_questions
  has_many :questions, :through => :evaluation_questions
  belongs_to :course, optional: true
  has_many :finished_evaluations
  accepts_nested_attributes_for :questions, reject_if: lambda {|attributes| attributes['content'].blank?}

  validates :name, presence: true, length: { minimum: 5 }

  scope :unassigned, -> {where(:course_id => nil)}
  scope :assigned, -> {where.not(:course_id => nil)}


end

ce-evals-app/app/views/evaluations/_evaluations_status.html.erb
<%= render 'evaluations_subnav' %>

 <ul>
    <% @evaluations.each do |e| %>
    <% if is_authorized?(e) %>
      <li class="col-12 d-block width-full py-4 border-bottom public source">
          <div class="d-inline-block mb-1">
            <h3>
              <%= link_to e.name, evaluation_path(e), itemprop: "name codeRepository" %>
            </h3>
          </div>
          <div class="f6 text-gray mt-2">
                <span class="mr-3" itemprop="programmingLanguage">
                  Class: <%= e.course.title unless e.course.nil? %>
                </span>
              Date: <%= e.course.start_date unless e.course.nil? %>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>

ce-evals-app/app/views/evaluations/_evaluations_subnav.html.erb
<div class="tabnav">
  <div class="float-right">
    <% unless is_attendee? %>
      <%= link_to "New Evaluation", new_evaluation_path, class: "tabnav-extra btn" %>
    <% end %>
  </div>
  <nav class="tabnav-tabs" aria-label="All Evaluations">

    <%= link_to evaluations_path, :class => current_page?(evaluations_path) do %>
      All Evaluations
      <span class="Counter"><%= evaluations_all_count %></span>
    <% end %>

    <%= link_to assigned_evaluations_path, :class => current_page?(assigned_evaluations_path) do %>
      Assigned Evaluations
      <span class="Counter"><%= evaluations_assigned_count %></span>
    <% end %>

    <%= link_to unassigned_evaluations_path, :class => current_page?(unassigned_evaluations_path) do %>
    Unassigned Evaluations
      <span class="Counter"><%= evaluations_unassigned_count%></span>
    <% end %>

  </nav>
</div>

ce-evals-app/app/views/evaluations/_form.html.erb
<%= form_for @evaluation, builder: PrimerFormBuilder do |f| %>
  <% if @evaluation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evaluation.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @evaluation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Evaluation Name" %>:
    <%= f.text_field :name %><br>
  </div>

<h3>Questions:</h3>
  <div class="field mx-5">

    <%= f.collection_check_boxes(:question_ids, questions_by_instructor, :id, :content) do |q| %>
      <%= q.label class:"form-checkbox" do%>
        <%=q.check_box + q.text%>
      <% end %>
      | <%= link_to 'Edit Question', edit_question_path(q.object.id, :ref_id => params[:id]) %></br>
    <% end %>
    <br>
  </div>

  <div class="field">
    <span>Add question:</span>
    <%= f.fields_for :questions, Question.new do |question_form| %>
      <%= question_form.text_field :content %>
      <% end %>
  </div>
<br />

<h3>Assign evaluation to course</h3>
  <div class="field mx-5">
    <%= f.collection_radio_buttons(:course_id, unassigned_courses, :id, :title) do |b| %>
      <%= b.label class:"form-checkbox" do%>
        <%=b.radio_button + b.text%> </br>
      <%end%>
    <% end %>
  </div>
  <br>

    <div class="actions">
      <%= f.submit :class => 'btn btn-primary' %>
    </div>
  <% end %>

ce-evals-app/app/views/evaluations/answers.html.erb
<h2>Evaluation for <%= @course.title %></h2>
<br />
<%= form_for(@finished_evaluation, url: {controller: "finished_evaluations", action: "create"}, method: :post) do |f| %>
  <h5>The learning objectives for this course were:</h5>
  <div class="mx-5"
  <ul>
    <li>
      <%= @course.learning_objective_1 %>
    </li>
    <li>
      <%= @course.learning_objective_2 %>
    </li>
    <li>
      <%= @course.learning_objective_3 %>
    </li>
  </ul>
</div>
<br />
  <table class="data-table">
    <thead>
      <tr>
        <th>Question</th>
        <th>Answer</th>
      </tr>
    </thead>
    <tbody>
      <% @evaluation.questions.each do |question| %>
      <tr>
        <td><%= question.content %></td>
        <td>
            <%= f.fields_for :answers, question.answers.create(attendee: @attendee) do |a| %>
              <% if question.text? %>
                <%= a.text_area :content %>
                <%= a.hidden_field :question_id, :value => question.id %>
                <%= a.hidden_field :attendee_id, :value => @attendee.id %>
              <% else %>
                <%= a.select :rating, [["Strongly Disagree", 1], ["Disagree", 2], ["Neutral", 3], ["Agree", 4], ["Strongly Agree", 5]] %>
                <%= a.hidden_field :question_id, :value => question.id %>
                <%= a.hidden_field :attendee_id, :value => @attendee.id %>
              <% end %>

          <% end %>

        </td>
      </tr>

      <% end %>
        <%= f.hidden_field :evaluation_id, :value => params[:id] %>
        <%= f.hidden_field :course_id, :value => @evaluation.course.id %>
        <%= f.hidden_field :attendee_id, :value => @attendee.id %>
      </tbody>
    </table>
    <br />
    <div class="actions">
      <%= f.submit :class => 'btn btn-primary' %>
    </div>
<% end -%>

ce-evals-app/app/views/evaluations/assigned.html.erb
<%= render 'evaluations_status' %>

ce-evals-app/app/views/evaluations/edit.html.erb
<h1>Editing Evaluation: <%= @evaluation.name %></h1>

<%= render 'form' %>

ce-evals-app/app/views/evaluations/index.html.erb
<%= render 'evaluations_status' %>

ce-evals-app/app/views/evaluations/new.html.erb
<h1>New Evaluation</h1>

<%= render 'form' %>

ce-evals-app/app/views/evaluations/show.html.erb
<h2>Evaluation: <%= @evaluation.name %></h2>
<br />
<h4>Questions</h4>
<div class="mx-5">
  <ul>
      <% @questions.each do |q| %>
      <li>
        <%= q.content %>
      </li>
      <% end %>
  </ul>
</div>
<br />

<h4>Assigned to Course</h4>
  <div class="mx-5">
      <% if !@evaluation.course.nil? %>
        <%= link_to @evaluation.course.title, @evaluation %>
      <% else %>
        Not assigned
      <% end %>
    </div>
<br />

<% if is_authorized?(@evaluation) && !@evaluation.finished_evaluations.any? %>
  <%= link_to 'Edit', edit_evaluation_path(@evaluation) , class: "btn" %> |
  <%= link_to 'Destroy', @evaluation, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

ce-evals-app/app/views/evaluations/unassigned.html.erb
<%= render 'evaluations_status' %>